### ISSUE TITLE
Does not work on Ubuntu 15.04 with Firefox 39.0

### ISSUE THREAD

**Issue by jonnius** [disconnectme/search#46]
I just installed the extension but my search is as was. No disconnect search availabe.

**Comment by disconnectme** [comment]
Hi,

Do you see the Disconnect Search icon in your Firefox toolbar (magnifying glass with a D in the middle)?   If not, is it listed in your FF add ons?

Thanks,
Gus

**Comment by jonnius** [comment]
Now I found the icon (via personalize). It won't replace the firefox's search bar?
